# مرحله ساخت (Build Stage)
FROM node:18-alpine AS builder

WORKDIR /app


COPY package*.json ./
RUN npm install


COPY . .


FROM node:18-alpine

WORKDIR /app


COPY --from=builder /app/node_modules ./node_modules
COPY . .


CMD ["tail", "-f", "/dev/null"]